# Generated by Django 3.1.7 on 2021-04-01 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=25)),
                ('price', models.DecimalField(decimal_places=3, max_digits=25)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('Categories', models.ManyToManyField(to='core.Category')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
