# Generated by Django 3.1.7 on 2021-04-17 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryNumber', models.CharField(max_length=255)),
                ('sentFrom', models.CharField(max_length=255)),
                ('sentTo', models.CharField(max_length=255)),
                ('contactPerson', models.CharField(blank=True, max_length=255)),
                ('fullAddress', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=25)),
                ('products', models.ManyToManyField(to='core.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
